### ISSUE TITLE
Decidir que framework de CSS vamos a usar

### ISSUE THREAD

**Issue by neftalyluis** [TachibanaLabs/congreso-app#17]
@Merak1 de esta lista elige los que más te gusten [Frameworks](https://github.com/troxler/awesome-css-frameworks/blob/master/readme.md)

@RogelioE escribe en este issue que tipo de página necesita el este vato

**Comment by RogelioE** [comment]
Quiere una landing page con fondo tipo parallax, más o menos como ya la tenía con el menú transparente y el icono del congreso en el mismo menú, como ya estaba
